version: '3'
services:
    mariadb:
        image: mariadb:10.2.9
        container_name: news_db
        hostname: news_db
        expose:
          - "3308"
        volumes:
          - ./data:/var/lib/mysql
          - /etc/localtime:/etc/localtime
        environment:
          - MYSQL_ROOT_PASSWORD=i4admin
        # networks:
        #   net:
        #     ipv4_address: 172.18.0.2
    web:
        image: php/7.2.10:latest
        container_name: news
        hostname: news
        privileged: true
        depends_on:
          - mariadb
        ports:
          - "7232:80"
          - "7233:443"
        expose:
          - "80"
          - "443"
        volumes:
          - ./www:/var/www/html/
          - ./logs:/var/log/apache2
          - ./conf:/etc/apache2/sites-enabled 
          - ./certs:/usr/local/apache2/certs
#         networks:
#           net:
#             ipv4_address: 172.23.0.3
# networks:
#     net:
#         driver: bridge
#         ipam:
#           config:
#           - subnet: 172.23.0.0/16
